---
# Set up ansible

- name: Install ansible
  tags:
    - packages
  ansible.builtin.apt:
    pkg:
      - ansible
    state: latest # noqa package-latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Create folder for ansible config
  ansible.builtin.file:
    path: "/etc/ansible"
    state: directory
    mode: 0700
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create the ansible inventory
  ansible.builtin.template:
    src: hosts
    dest: /etc/ansible/hosts
    mode: 0600
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create the ansible config
  ansible.builtin.template:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    mode: 0600
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create the ansible ssh key
  ansible.builtin.template:
    src: ssh.key
    dest: /etc/ansible/ssh.key
    mode: 0600
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create the vault password
  ansible.builtin.template:
    src: password.txt
    dest: /etc/ansible/password.txt
    mode: 0600
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
