---
- name: Restart DD Agent
  ansible.builtin.systemd:
    state: restarted
    name: datadog-agent
    enabled: true

- name: Restart Edge Service
  ansible.builtin.systemd:
    state: restarted
    name: edge
    enabled: true
    daemon_reload: true
